version: 2.1
jobs:
  build:
    docker: 
      - image: python:alpine3.7
    working_directory: ./Flask_Docker_Demo
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: 
          name: list directories
          command: ls
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: upload to bintray
          command: ./jfrog rt config --url https://dl.bintray.com/akashorg/flask_circle_ci --user akash306 --apikey d48f02dffa6e4180b251a4b1aad36df452cef3fb --interactive=false
                   ./jfrog rt u <path/to/artifact> akashorg-docker-flask_circle_ci.bintray.io --build-name=flask_docker_image --build-number=1
                   ./jfrog rt bce flask_docker_image 1  # collects all environment variables on the agent
                   ./jfrog rt bp flask_docker_image 1  # attaches ^^ to the build in artifactory
      - run:
          name: run server
          command: python Flask_Code.py
      
          
      
