version: 2.1
orbs:
    win: circleci/windows@2.2.0
jobs:
  build_pyinstaller_executable:
    executor: win/default
    steps:
      - checkout
      - run: 
          name: Check Code availability
          command: dir
      - run: 
          name: Check Python Version
          command: python --version
      - run: 
          name: Install Dependency
          command: |
            pip install -r requirements.txt
      - run:
          name: Create Pyinstaller Setup
          command: |
            pyinstaller Flask_Code.py
      - run: 
          name: Check the Directory
          command: dir
      - run: 
          name: Check the Directory
          command: | 
            cd dist
            dir
      - run: 
          name: Create ZIP of Pyinstaller O/P
          command: |
            cd dist
            tar -cf Flask_Code.zip Flask_Code
      - run: 
          name: Copy Project to Bintray
          command: curl --upload-file Flask_Code.zip -uakash306:$API_KEY https://api.bintray.com/content/akashorg/Flask_Project_Executable/Flask_Zip_File/0.0/FirstZip
workflows:
  version: 2
  build-master:
    jobs:
      - build_pyinstaller_executable:
          filters:
            branches:
              only: master

            
