version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: akku306/flask_docker_image
    docker: 
      - image: python:alpine3.7
    working_directory: ./Flask_Docker_Demo
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: 
          name: list directories
          command: ls
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run server
          command: python Flask_Code.py
  publish-latest:
    steps:
      - run:
          name: push image to docker hub
          command: |
            docker login akku306 41cf3981-2426-4844-97aa-ce009a4a683a
            docker push ${IMAGE_NAME}:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
              branches:
                only: master 
          
      
