version: 2.1
jobs:
  build_docker_image:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 
          name: Check Code availability
          run: dir  

  workflows:
  version: 2
  build-master:
    jobs:
      - build_pyinstaller_executable:
          filters:
            branches:
              only: master

            
