version: 2.1
orbs:
    win: circleci/windows@2.2.0
jobs:
  build_pyinstaller_executable:
    executor: win/default
    steps:
      - checkout
      - run: 
          name: Check Code availability
          command: dir
      - run:
          name: Download Python in Windows Machine
          command: |
            $ProgressPreference = "SilentlyContinue"
            Invoke-WebRequest https://www.python.org/ftp/python/3.8.0/python-3.8.0.exe -OutFile python38.exe
          shell: powershell.exe
      - run:
          name: Install Python in Windows Machine
          command: |
            python38.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 TargetDir=C:\Python38
            dir C:/
          shell: powershell.exe
      - run: 
          name: Check Python Version
          command: python --version
      - run: 
          name: Install Dependency
          command: |
            pip install -r requirements.txt
      - run:
          name: Create Pyinstaller Setup
          command: |
            pyinstaller Flask_Code.py
      - run: 
          name: Check the Directory
          command: dir
      - run: 
          name: Check the Directory
          command: | 
            cd dist
            dir
      - run: 
          name: Create ZIP of Pyinstaller O/P
          command: |
            cd dist
            tar -cf Flask_Code.zip Flask_Code
      - run: 
          name: Copy Project to Bintray
          command: |
            cd dist
            dir
            curl.exe --upload-file Flask_Code.zip -uakash306:$api_key https://api.bintray.com/content/akashorg/Flask_Project_Executable/Flask_Zip_File/0.0/FirstZip
workflows:
  version: 2
  build-master:
    jobs:
      - build_pyinstaller_executable:
          filters:
            branches:
              only: master