version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: akku306/flask_docker_image
    docker: 
      - image: python:alpine3.7
    working_directory: ./Flask_Docker_Demo
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker
      - run: echo "hello world" # run the `echo` command
      - run: 
          name: list directories
          command: ls
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: push image to docker hub
          command: |
            docker login $docker_user $docker_password
            docker push akku306/flask_docker_image:latest
      - run:
          name: run server
          command: python Flask_Code.py
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
