version: 2.1
orbs:
    win: circleci/windows@2.2.0
jobs:
  build_pyinstaller_executable:
    executor: win/default
    steps:
      - checkout
      - run: 
          name: Check Code availability
          command: dir
      - run: 
          name: Check Python Version
          command: python --version
      - run: 
          name: Install Dependency
          command: |
            python -m venv flaskvenv
            . flaskvenv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Create Pyinstaller Setup
          command: pyinstaller Flask_Code.py
workflows:
  version: 2
  build-master:
    jobs:
      - build_pyinstaller_executable:
          filters:
            branches:
              only: master

            
