version: 2.1
orbs:
    win: circleci/windows@2.2.0
jobs:
  build_pyinstaller_executable:
    executor: windows-default
    steps:
      - checkout
      - run: 
          name: Check Code availability
          command: dir  

workflows:
  version: 2
  build-master:
    jobs:
      - build_pyinstaller_executable:
          filters:
            branches:
              only: master

            
