version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: akku306/flask_docker_image
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: echo "hello world" # run the `echo` command
      - run: ls
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            sudo tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run: 
          name: Check docker version
          command: docker info
      - run: 
          name: docker login
          command: docker login -u $docker_user -p $docker_password
      - run: 
          name: create docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run: 
          name: push docker image to docker hub
          command: docker push $IMAGE_NAME:latest
  run_docker_image:
    environment:
      IMAGE_NAME: akku306/flask_docker_image
    docker:
      image: akku306/flask_docker_image:latest
    steps:
      - setup_remote_docker
      - run: 
          name: run docker image
          command: docker run -p 5010:5010 $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - run_docker_image:
          requires:
            - build
            
