version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: akku306/flask_docker_image
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: echo "hello world" # run the `echo` command
      - run: ls
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Check docker version
          command: docker --info
	  - run:
		  name: docker login
		  command: docker login $docker_user $docker_password
	  - run:
		  name: Create image
		  command: docker build -t $IMAGE_NAME:latest .
	  - run:
		  name: Push image to Docker Hub
		  command: docker push $IMAGE_NAME:latest	
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
