version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: akku306/flask_docker_image
    docker: 
      - image: python:alpine3.7
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker
      - run:
          name: create docker image
          command: docker build -t $IMAGE_NAME:lastest .
      - run:
          name: push image to docker hub
          command: |
            docker login $docker_user $docker_password
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
