version: 2.1
jobs:
  build_pyinstaller_executable:
    machine:
      image: windows-default
    steps:
      - checkout
      - run: 
          name: Check Code availability
          run: dir  

workflows:
build-master:
  jobs:
    - build_pyinstaller_executable:
        filters:
          branches:
            only: master

            
